spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/topik-e-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openapi:
  service:
    api-docs: TEL-be
    title: Topik E-Learning
    version: v1.0.0
    server: http://localhost:8080
jwt:
  secretKey: topikDev@Env

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
